name: VPS-starter-containers

networks:
  caddy:
    driver: bridge

services:

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    volumes:
      - ./containers/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./containers/caddy/site:/srv
      - ./containers/caddy/caddy_data:/data
      - ./containers/caddy/caddy_config:/config
    networks:
      - caddy

  portainer:
    image: portainer/portainer-ce:2.21.1
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./containers/portainer/portainer-data:/data
    expose:
      - 9000:9000
    networks:
      - caddy

  jenkins:
    image: jenkins-docker:latest
    user: root
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./containers/jenkins/jenkins_home:/var/jenkins_home
    group_add:
      - ${DOCKER_SOCK_GROUP_ID}
    networks:
      - caddy

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./containers/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - caddy

volumes:
  caddy_data:
    external: true
  caddy_config:
  postgres_data:
    driver: local