FROM jenkins/jenkins:jdk21

# Docker install
USER root
RUN apt-get update && apt-get install -y \
       apt-transport-https \
       ca-certificates \
       curl \
       gnupg2 \
       software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88
RUN add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) \
       stable"
RUN apt-get update && apt-get install -y docker-ce-cli

# Add Docker group and add Jenkins user to it
RUN if ! getent group docker; then \
       GID=$(awk -F: '{if ($3 >= 1000 && $3 < 65534) print $3}' /etc/group | sort -n | tail -1); \
       groupadd -g $((GID+1)) docker; \
    fi
RUN usermod -aG docker jenkins

# Ensure Docker socket has the correct group permissions
RUN touch /var/run/docker.sock && chown root:docker /var/run/docker.sock

USER jenkins